version: "3.8"

services:
  hardhat:
    build: ./hardhat
    environment:
      - CONTRACT_NAME=${CONTRACT_NAME}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - NETWORK=${NETWORK}
      - NETWORK_URL=${NETWORK_URL}
      - CHAIN_ID=${CHAIN_ID}
      - HARDHAT_HTTP_PORT=${HARDHAT_HTTP_PORT}
    volumes:
      - ./hardhat:/app
    ports:
      - "${HARDHAT_HTTP_PORT}:${HARDHAT_HTTP_PORT}"
      - "8545:8545"
    networks:
      - evm-network

  backend:
    build: ./backend
    depends_on:
      - hardhat
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - HTTP_PORT=${HTTP_PORT}
      - HARDHAT_CONTRACTS_URL=${HARDHAT_CONTRACTS_URL}
      - HARDHAT_ACCOUNTS_URL=${HARDHAT_ACCOUNTS_URL}
      - HARDHAT_HTTP_PORT=${HARDHAT_HTTP_PORT}
      - NETWORK=${NETWORK}
      - NETWORK_URL=${NETWORK_URL}
      - CHAIN_ID=${CHAIN_ID}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - ./backend:/app
      - ./wait-for-it.sh:/wait-for-it.sh
    working_dir: /app
    command: ./wait-for-it.sh hardhat:8545 -- npm run start
    networks:
      - evm-network

networks:
  evm-network:
    driver: bridge
