version: '3.8'

services:
  hardhat:
    build: ./hardhat
    environment:
      INFURA_PROJECT_ID: ${INFURA_PROJECT_ID}
      PRIVATE_KEY: ${PRIVATE_KEY}
    volumes:
      - ./hardhat:/app
    depends_on:
      - backend
    command: >
      /bin/sh -c "sleep 10 && npx hardhat run scripts/deploy.js --network rinkeby"

  backend:
    build: .
    environment:
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - PORT=${PORT}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start
