version: "3.8"

services:
  hardhat:
    build: ./hardhat
    environment:
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - NETWORK=${NETWORK}
    volumes:
      - ./hardhat:/app
    depends_on:
      - backend
    command: >
      /bin/sh -c "sleep 10 && npm install && npm run deploy"

  backend:
    image: node:16
    environment:
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PORT=${PORT}
      - NETWORK=${NETWORK}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run start"
